### ISSUE TITLE
Can you provide references?

### ISSUE THREAD

**Issue by luowy1001** [ColasGael/Automatic-Video-Colorization#2]
Thanks for your work! Which algorithm is used to complete the video coloring?
@ColasGael

**Comment by ColasGael** [comment]
HI @luowy1001 

Thanks for your interest, our work mostly extends a network used for image colorization to try to do color propagation.

The original paper is: Kamyar Nazeri, Eric Ng, and Mehran Ebrahimi. Image colorization using generative
adversarial networks. In International Conference on Articulated Motion and Deformable
Objects, pages 85–94. Springer, 2018

We added a new conditioning on the previous color frame to try to propagate colors from one frame to another.

You can see our report ("automatic-video-colorization.pdf") at the root for more details about the conditioning. It also explains (and shows) why this approach is bound to failing due to exponential error propagation.

Some recent papers on Video Colorization came up after the end of our project.
The following repository is the code of one of the state-of-the-art algorithm: https://github.com/msracver/Deep-Exemplar-based-Colorization
